from langchain_core.tools import tool
from typing import List, Dict, Any


@tool
def get_service_metrics(service_name: str) -> Dict[str, Any]:
    """
    Retrieve the latest metrics for a specific service.

    This tool returns the current performance metrics of a service,
    including CPU usage, memory usage, latency, and error rate.

    Use this tool when:
    - You need to analyze abnormal system behavior
    - You want to compare current values against expected thresholds
    - You suspect performance degradation in a specific service

    Input:
    - service_name (str): The exact name of the service (e.g., "auth-service", "api-gateway")

    Output:
    - A dictionary containing:
        {
            "cpu": float (percentage, 0–100),
            "memory": float (percentage, 0–100),
            "latency": float (milliseconds),
            "error_rate": float (percentage)
        }

    Notes:
    - Values represent the latest snapshot of system state
    - High memory or latency may indicate performance issues
    - Increasing error_rate often indicates failures or bugs
    """
    # Dummy implementation (to be replaced later)
    return {
        "cpu": 50.0,
        "memory": 75.0,
        "latency": 120.0,
        "error_rate": 2.0
    }


@tool
def get_service_logs(service_name: str) -> List[Dict[str, Any]]:
    """
    Retrieve recent logs for a specific service.

    This tool returns a list of recent log entries generated by the service.
    Logs are essential for diagnosing issues, identifying error patterns,
    and understanding system behavior.

    Use this tool when:
    - You are investigating an alert or anomaly
    - You need to identify error messages or stack traces
    - You want to understand what happened before a failure

    Input:
    - service_name (str): The exact name of the service (e.g., "auth-service")

    Output:
    - A list of log dictionaries:
        [
            {
                "timestamp": str (ISO format),
                "service": str,
                "level": str ("INFO", "DEBUG", "ERROR"),
                "message": str
            }
        ]

    Notes:
    - ERROR logs are especially important for root cause analysis
    - Repeated patterns in logs may indicate systemic issues
    - Logs are ordered from oldest to newest
    """
    # Dummy implementation
    return [
        {
            "timestamp": "2026-04-27T10:00:00",
            "service": service_name,
            "level": "ERROR",
            "message": "OutOfMemoryError: heap space exceeded"
        },
        {
            "timestamp": "2026-04-27T10:00:01",
            "service": service_name,
            "level": "ERROR",
            "message": "Memory allocation failed during JWT decode"
        }
    ]


@tool
def restart_service(service_name: str) -> str:
    """
    Restart a given service to recover from failures.

    This tool simulates restarting a service. Restarting can resolve issues such as:
    - Memory leaks
    - Stuck processes
    - Temporary system overload

    Use this tool when:
    - A service is in a degraded or failed state
    - Errors indicate resource exhaustion (e.g., memory leak)
    - A quick recovery action is required

    Input:
    - service_name (str): The exact name of the service

    Output:
    - A string confirmation message indicating the service has been restarted

    Notes:
    - Restarting may temporarily disrupt service availability
    - This is typically used as a short-term fix, not a permanent solution
    """
    # Dummy implementation
    return f"{service_name} restarted successfully"