from langchain_core.tools import tool
from typing import List, Dict, Any
from memory.incident_memory import search_past_incidents
from simulator.state import env


@tool
def get_service_metrics(service_name: str) -> Dict[str, Any]:
    """
    Retrieve the latest metrics for a specific service.

    This tool returns the current performance metrics of a service,
    including CPU usage, memory usage, latency, and error rate.

    Use this tool when:
    - You need to analyze abnormal system behavior
    - You want to compare current values against expected thresholds
    - You suspect performance degradation in a specific service

    Input:
    - service_name (str): The exact name of the service (e.g., "auth-service", "api-gateway")

    Output:
    - A dictionary containing:
        {
            "cpu": float (percentage, 0–100),
            "memory": float (percentage, 0–100),
            "latency": float (milliseconds),
            "error_rate": float (percentage)
        }

    Notes:
    - Values represent the latest snapshot of system state
    - High memory or latency may indicate performance issues
    - Increasing error_rate often indicates failures or bugs
    """
    for svc in env.services:
        if svc.name == service_name:
            return svc.metrics.model_dump()
    return {"error": f"Service '{service_name}' not found"}


@tool
def get_service_logs(service_name: str) -> List[Dict[str, Any]]:
    """
    Retrieve recent logs for a specific service.

    This tool returns a list of recent log entries generated by the service.
    Logs are essential for diagnosing issues, identifying error patterns,
    and understanding system behavior.

    Use this tool when:
    - You are investigating an alert or anomaly
    - You need to identify error messages or stack traces
    - You want to understand what happened before a failure

    Input:
    - service_name (str): The exact name of the service (e.g., "auth-service")

    Output:
    - A list of log dictionaries:
        [
            {
                "timestamp": str (ISO format),
                "service": str,
                "level": str ("INFO", "DEBUG", "ERROR"),
                "message": str
            }
        ]

    Notes:
    - ERROR logs are especially important for root cause analysis
    - Repeated patterns in logs may indicate systemic issues
    - Logs are ordered from oldest to newest
    """
    from simulator.state import last_logs
    return [log for log in last_logs if log.get("service") == service_name] or [
        {"timestamp": "-", "service": service_name, "level": "INFO",
         "message": "No recent logs available for this service."}
    ]


@tool
def restart_service(service_name: str) -> str:
    """
    Restart a given service to recover from failures.

    This tool simulates restarting a service. Restarting can resolve issues such as:
    - Memory leaks
    - Stuck processes
    - Temporary system overload

    Use this tool when:
    - A service is in a degraded or failed state
    - Errors indicate resource exhaustion (e.g., memory leak)
    - A quick recovery action is required

    Input:
    - service_name (str): The exact name of the service

    Output:
    - A string confirmation message indicating the service has been restarted

    Notes:
    - Restarting may temporarily disrupt service availability
    - This is typically used as a short-term fix, not a permanent solution
    """
    # Find and resolve any active incident on this service so the
    # simulation stops injecting degraded metrics next tick.
    resolved = []
    for inc in list(env.active_incidents):
        if inc.service == service_name:
            env.resolve_incident(inc.name)
            resolved.append(inc.name)

    if resolved:
        return f"{service_name} restarted successfully. Resolved incidents: {', '.join(resolved)}"
    return f"{service_name} restarted successfully"

@tool
def query_incident_memory(symptoms: str) -> str:
    """
    Search historical incident memory for similar symptoms.

    Use this tool FIRST before performing deep investigation.
    Historical incidents may contain useful root causes
    and remediation strategies.

    Input:
    - symptoms (str): Current incident symptoms, errors,
      or abnormal behavior observed in the system.

    Output:
    - A formatted string containing similar past incidents
    - Returns "No past incidents found." if memory is empty
      or no similar incidents exist.
    """

    results = search_past_incidents(symptoms)

    documents = results.get("documents", [])

    # No matches found
    if not documents or not documents[0]:
        return "No past incidents found."

    # Format incidents for LLM readability
    formatted_results = []

    for idx, doc in enumerate(documents[0], start=1):
        formatted_results.append(
            f"Past Incident #{idx}:\n{doc}"
        )

    return "\n\n".join(formatted_results)
